services:
  constructor_db:
    container_name: constructor_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  constructor_db:
