services:
  constructor_db:
    container_name: constructor_db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      constructor_db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:5432/{POSTGRES_DB}?sslmode=disable
    volumes:
      - ./migrations:/app/migrations
      - ./.env:/app/.env
    ports:
      - "8080:8080"


volumes:
  constructor_db:
