basePath: /api
definitions:
  dao.PwaCreateRequest:
    properties:
      iconUrl:
        type: string
      name:
        type: string
      type:
        $ref: '#/definitions/enums.TypeCampaign'
    type: object
  enums.TypeCampaign:
    enum:
    - 0
    - 1
    - 2
    type: integer
    x-enum-varnames:
    - GoogleBlue
    - GoogleGreen
    - AppleStore
host: localhost:8080
info:
  contact: {}
  description: App for landing constructor.
  title: Gin Swagger Landing Constructor
  version: "1.0"
paths:
  /common:
    get:
      consumes:
      - application/json
      description: Pinging for server and app
      produces:
      - application/json
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Router for ping
      tags:
      - Common
  /pwa:
    post:
      consumes:
      - application/json
      description: Создает новый PWA на основе переданных данных
      parameters:
      - description: Данные для создания PWA
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dao.PwaCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Успешное создание PWA
        "400":
          description: Неверный формат запроса
        "500":
          description: Ошибка сервера при создании PWA
      summary: Создание нового PWA
      tags:
      - PWA
swagger: "2.0"
